### ISSUE TITLE
"Something went wrong. Please try again some time." when create event

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-employeetraining#5]
Hi team, we cannot create event after deploy the app, and prompted error "Something went wrong. Please try again some time."
Please kindly advise how can I fix the error, thanks :)

![image](https://user-images.githubusercontent.com/25476072/100948615-38629d80-3543-11eb-8205-30c5f4d73dd9.png)

**Comment by yalcindizdar** [comment]
The same here ! 

Thanks for advise on fixing this...

**Comment by Madhan-MSFT** [comment]
Is this an intermittent issue?

**Comment by yalcindizdar** [comment]
Hi Madhan,

No, the issue is permanent. We still have the same problem. We also experienced the same issue on  a client installation yesterday. We replicate the issue in every installation.

**Comment by rex-ma** [comment]
The issue is not intermittent.

**Comment by gracesivaya** [comment]
We replicate this issue in different environments and are unable to proceed. Please advise how to mitigate.

**Comment by Ochuwa-sophie** [comment]
Having this same issue.

**Comment by Zunade** [comment]
Hi All

Enabled Application Insights for the app under app services, everything started to work

**fixed**:
- able to add categories
- able to add events

![image](https://user-images.githubusercontent.com/73882158/111815321-351dd280-88e4-11eb-8fa7-74d588b5bd41.png)

![image](https://user-images.githubusercontent.com/73882158/111814781-8da0a000-88e3-11eb-98b6-74b7b6406fb0.png)
![image](https://user-images.githubusercontent.com/73882158/111815251-1fa8a880-88e4-11eb-859d-705c5edb90c2.png)

**Comment by Ochuwa-sophie** [comment]
Trying this now,

**Comment by Frajhm** [comment]
Same issue.  Tried the app insights but still getting the same.

**Comment by Ochuwa-sophie** [comment]
Same, didn't fix for mine

**Comment by thechrissou** [comment]
Exact same issue here. Not able to solve with enabling Insights.

**Comment by mvidal365** [comment]
Same issue here

**Comment by littleaggieiscoding** [comment]
Anyone in this thread was successful in resolving the issue of adding new categories?

**Comment by divim** [comment]
Enabled app insights and it worked!

**Comment by mustafafarooq** [comment]
I have redeployed numerous times, enabled insights , disabled and then re-enabled insights, but this is still not working for me ? Please share a solution to this
